### ISSUE TITLE
Setup Usage Problem

### ISSUE THREAD

**Issue by mehmetsarr** [froger-me/wp-packages-update-server#24]
Hello, thank you for this plugin. How to integrate this plugin into our own server and theme to be updated, and is there a video tutorial for general use?

**Comment by froger-me** [comment]
Hi @mehmetsarr !
Happy you're interested in my work! First, I need to mention I am not actively supporting the plugin anymore as stated in the README file.
With that out of the way, the answer to your question lies in the example plugin and theme packed in the [integration-examples](https://github.com/froger-me/wp-plugin-update-server/tree/master/wp-plugin-update-server/integration-examples): these are package skeletons fully commented.
I did not release any video, because aside from the two skeletons, the interface is completed with inline help, and there is rather prolific documentation. It is a plugin for developers that wasn't designed to be fully plug'n'play for the sake of avoiding making too many assumptions.
