### ISSUE TITLE
Can't download theme from a subgroup on gitlab.com and JS Error: $(...).datepicker is not a function main.js:337:27

### ISSUE THREAD

**Issue by khartahk** [froger-me/wp-packages-update-server#4]
WP Core Version 4.9.8
WP Plugin Update Server Version 1.4.8

I've tried to use `gitlab.com/group/subgroup` as `Remote repository service URL` and when I try to get the theme by `Get remote package` the spinner never stops spinning.

Also I got this error in the JS console.
```
TypeError: $(...).datepicker is not a function main.js:337:27
<anonimno> https://DOMAIN.TLD/wp-content/plugins/wp-plugin-update-server/js/admin/main.js:337:27
i https://DOMAIN.TLD/wp-admin/load-scripts.php:2:27444
fireWith https://DOMAIN.TLD/wp-admin/load-scripts.php:2:28213
ready https://DOMAIN.TLD/wp-admin/load-scripts.php:2:30004
K https://DOMAIN.TLD/wp-admin/load-scripts.php:2:30366
```
Perhpas these two issues are related?

**Comment by froger-me** [comment]
Hello @khartahk !
Thank you for reaching out and bringing these issues to my attention.

I say issues (plural) because the javascript error is not related to the package not found issue:
- subgroups are not supported at this time, and there is currently no plan for it: the idea is to keep the same structure `https://repository-service.tld/username` across the board (or, `https://gitlab.com/group` in the case of Gitlab). I will add this precision to the inline help, as well as the proper validation
- the js error is of no consequence in the `Overview` tab, and I will make sure to add the proper control structure to use the `datepicker` function only where needed.

The changes outlined above will be out in v1.4.9 later this week - in the meantime, as I just tested, you should be able to use the plugin without issues if you do not include subgroups in the remote service URL.

Thanks!

**Comment by froger-me** [comment]
Changes made and pushed - closing
